name: CI

on:
  push:
    branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run detekt
        run: ./gradlew detekt

      - name: Run tests
        run: ./gradlew test